### ISSUE TITLE
RN 0.63 >= android couldn't find DSO to load: libhermes.so

### ISSUE THREAD

**Issue by EliYenn** [ivpusic/react-native-image-crop-picker#1072]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.0
- react-native v0.63 >= 

### Platform
- Android

### Actual behaviour
cash  of  android but debug successful

### Steps to reproduce

I init new project (RN0.64) ,According to the guide  ,add in my project than run for android。ios fine,only android

I add line to android/build.gradle behind this guide.Is work for me !

        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

### Attachments
log this 

E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.gamescompetitive, PID: 24204
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:764)
I/Process: Sending signal. PID: 24204 SIG: 9

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by ivpusic** [comment]
issue is not related to this library
