### ISSUE TITLE
Provide more unique ActivityEvenListener requestCodes

### ISSUE THREAD

**Issue by kylejones** [ivpusic/react-native-image-crop-picker#111]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.0
- react-native v0.35.0

### Platform
Tell us to which platform this issue is related

- Android

### Steps to reproduce

I'm running react-native-image-picker and react-native-braintree-xplat. Both have ActivityEventListeners with a requestCode of 1. The collision in requestCodes causes app crashes when one module tries to handle the request from the other. I would suggest using a large random integer to reduce the likelihood of collisions with other modules.

https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L48

Stack trace
```sh
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/60 flg=0x1 }} to activity {com.seejanego/com.seejanego.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.braintreepayments.api.models.PaymentMethodNonce.getNonce()' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
    at android.app.ActivityThread.-wrap16(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.braintreepayments.api.models.PaymentMethodNonce.getNonce()' on a null object reference
    at com.pw.droplet.braintree.Braintree.onActivityResult(Braintree.java:116)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
    at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:620)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
    at android.app.Activity.dispatchActivityResult(Activity.java:6428)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
    at android.app.ActivityThread.-wrap16(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ivpusic** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/pull/112

**Comment by ivpusic** [comment]
released in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.10.1
