### ISSUE TITLE
App crashes on multiple open

### ISSUE THREAD

**Issue by wojcikiewiczm** [ivpusic/react-native-image-crop-picker#1123]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.25.2
- react-native v0.60.0

Hi my app is crashing when I open and pick image multiple times in a row (it's random but it's between 4 and 7 times) on Android (API 25). I'm using single picker without crop. 

```
   ImagePicker.openPicker({}).then(response => {
        if (response.path) {
          addPhoto({value: response.path, key: photoType}); // redux state
          closeModal();
        }
    });
```
```
2019-09-24 11:38:05.787 1627-1627/com.fixummobileapp E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 543424)
2019-09-24 11:38:06.228 1627-1627/com.fixummobileapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fixummobileapp, PID: 1627
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 543424 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: android.os.TransactionTooLargeException: data parcel size 543424 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1142)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3890)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by soumen1808** [comment]
Facing the same issue with my app. Crashes happen on selecting multiple images one after another(from 2 to 9 times in my case).

- react-native-image-crop-picker v0.24.1
- react-native v0.59.8

        buildToolsVersion = "28.0.3"                                            
        minSdkVersion = 21                                                      
        compileSdkVersion = 28                                                  
        targetSdkVersion = 28                                                   
        supportLibVersion = "28.0.0" 

Testing app on Motorola G4 Plus (Android 7.0)

```
10-16 23:42:15.506  2094  2452 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-16 23:42:15.506  2094  2452 E AndroidRuntime: Process: com.vincentlabs.vincent, PID: 2094
10-16 23:42:15.506  2094  2452 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'glesVersion.split'), stack:
10-16 23:42:15.506  2094  2452 E AndroidRuntime: getGl@107016:48
10-16 23:42:15.506  2094  2452 E AndroidRuntime: _onSurfaceCreate@106122:23
10-16 23:42:15.506  2094  2452 E AndroidRuntime: invokeGuardedCallbackImpl@8538:21
10-16 23:42:15.506  2094  2452 E AndroidRuntime: invokeGuardedCallback@8629:42
10-16 23:42:15.506  2094  2452 E AndroidRuntime: invokeGuardedCallbackAndCatchFirstError@8633:36
10-16 23:42:15.506  2094  2452 E AndroidRuntime: executeDispatch@8827:48
10-16 23:42:15.506  2094  2452 E AndroidRuntime: executeDispatchesInOrder@8847:26
10-16 23:42:15.506  2094  2452 E AndroidRuntime: executeDispatchesAndRelease@8942:35
10-16 23:42:15.506  2094  2452 E AndroidRuntime: forEachAccumulated@8934:18
10-16 23:42:15.506  2094  2452 E AndroidRuntime: runEventsInBatch@9036:27
10-16 23:42:15.506  2094  2452 E AndroidRuntime: runExtractedEventsInBatch@9043:25
10-16 23:42:15.506  2094  2452 E AndroidRuntime: <unknown>@10010:36
10-16 23:42:15.506  2094  2452 E AndroidRuntime: batchedUpdates$1@21216:20
10-16 23:42:15.506  2094  2452 E AndroidRuntime: batchedUpdates@9952:37
10-16 23:42:15.506  2094  2452 E AndroidRuntime: _receiveRootNodeIDEvent@10009:23
10-16 23:42:15.506  2094  2452 E AndroidRuntime: receiveEvent@10015:32
10-16 23:42:15.506  2094  2452 E AndroidRuntime: __callFunction@2580:49
10-16 23:42:15.506  2094  2452 E AndroidRuntime: <unknown>@2337:31
10-16 23:42:15.506  2094  2452 E AndroidRuntime: __guard@2534:15
10-16 23:42:15.506  2094  2452 E AndroidRuntime: callFunctionReturnFlushedQueue@2336:21
10-16 23:42:15.506  2094  2452 E AndroidRuntime: callFunctionReturnFlushedQueue@-1
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
10-16 23:42:15.506  2094  2452 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```
