### ISSUE TITLE
User cancelled image selection

### ISSUE THREAD

**Issue by thehappydinoa** [ivpusic/react-native-image-crop-picker#1257]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.28.0
- react-native v0.61.5

### Platform
Tell us to which platform this issue is related

- iOS  13.3.1(17D50)

### Expected behaviour

Open Image Picker

### Actual behaviour

Once we open camera then open image picker, it opens image picker and then immediately closes.

### Steps to reproduce

1. Call `openPicker`

2. Have `User cancelled image selection` raised and picker closed

### Attachments

```javascript
let pickImage = async (multiple = false) => {
  return new Promise(resolve => {
    ImagePicker.openPicker({
      cropping: true,
      mediaType: 'photo',
      includeBase64: true,
      multiple,
    }).then(image => {
      if (multiple) {
        resolve([
          ...image.map(i => ({
            image: {
              uri: i.path,
              name: 'cropped',
              type: i.mime,
            },
            encodedImage: `data:${i.mime};base64,${i.data}`,
          })),
        ]);
      } else {
        resolve({
          image: {
            uri: image.path,
            name: 'cropped',
            type: image.mime,
          },
          encodedImage: `data:${image.mime};base64,${image.data}`,
        });
      }
    });
  });
};
```

```
Error: User cancelled image selection
  at Promise$argument_0(app:///uploadImage.js:4:21)
  File "app:///core.js", col 7, in tryCallTwo
  File "app:///core.js", col 23, in doResolve
  File "app:///core.js", col 12, in Promise
  at pickImage(app:///uploadImage.js:3:16)
  File "app:///runtime.js", col 44, in tryCatch
  File "app:///runtime.js", col 30, in invoke
  File "app:///runtime.js", col 44, in tryCatch
  File "app:///runtime.js", col 28, in invoke
  File "app:///runtime.js", col 17, in Promise$argument_0
  File "app:///core.js", col 7, in tryCallTwo
  File "app:///core.js", col 23, in doResolve
  File "app:///core.js", col 12, in Promise
  File "app:///runtime.js", col 27, in Promise$argument_0
  File "app:///runtime.js", col 38, in enqueue
  File "app:///runtime.js", col 8, in exports.async
  at pickImage(app:///uploadImage.js:3:16)
  at <unknown>(app:///index.bundle?platform=ios&dev=true&minify=false:179306:36)
  at TouchableDebounce(app:///UI.js:55:16)
  File "app:///underscore.js", col 8, in restArguments$argument_0
  File "app:///underscore.js", col 8, in <anonymous>
  File "app:///TouchableOpacity.js", col 45, in createReactClass$argument_0.touchableHandlePress
  File "app:///[native code]", in touchableHandlePress
  File "app:///Touchable.js", col 34, in TouchableMixin._performSideEffectsForTransition
  File "app:///[native code]", in _performSideEffectsForTransition
  File "app:///Touchable.js", col 44, in TouchableMixin._receiveSignal
  File "app:///[native code]", in _receiveSignal
  File "app:///Touchable.js", col 24, in TouchableMixin.touchableHandleResponderRelease
  File "app:///[native code]", in touchableHandleResponderRelease
  File "app:///[native code]", in forEach
  File "app:///[native code]", in callFunctionReturnFlushedQueue
```

**Comment by ngregrichardson** [comment]
I've been having the same issue on iOS 13.3.1 as well

**Comment by uchar** [comment]
Same problem here on iOS 13.4.1

**Comment by jonocairns** [comment]
I've had this as well - this was my temp workaround

```

    const imgs = await ImagePicker.openPicker({
      multiple: true,
    }).catch(e => {
      if (e.code !== 'E_PICKER_CANCELLED') {
        console.log(e);
        Alert.alert('Sorry, there was an issue attempting to get the image/video you selected. Please try again');
      }
    });

```

Seems weird that you cannot try catch the async await here as well :(

**Comment by samuk190** [comment]
hey guys, you need catch the error, and no the error is not _E_PICKER_CANCELLED, the error is "user cancelled" something like that
but just in case, you can use a general error
Look at my code. You should get the ERROR after the .then
function handleFile() {
    ImagePicker.openPicker({
      width: 300,
      height: 400,
      cropperCircleOverlay: true,
      cropping: true,
      includeBase64: true,
    })
      .then((image) => {
        setFile(image);
        setFileUrl(`data:${image.mime};base64,${image.data}`);
        RNToasty.Warn({
          title: 'Não se esqueça de salvar as alterações! ',
        });
      })
      .catch((e) => {
        // console.log(e);

        // console.log(e);
        RNToasty.Info({
          title: 'Você cancelou a seleçao do avatar! ',
        });
      });
