### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown color

### ISSUE THREAD

**Issue by ObidosDev** [ivpusic/react-native-image-crop-picker#1259]
### Version
- react-native-image-crop-picker v0.28.0
- react-native v0.61.5

### Platform
Android

### Expected behaviour
Use any string representation of color (react-native) OR should be described in the doc

### Actual behaviour
Supports only color which starts with "#"

### Steps to reproduce
1. Use for any of "color" variables "rgba(255, 200, 200, 1)"

### Attachments
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:7185 flg=0x1 }} to activity {package/com.findo.MainActivity}: java.lang.IllegalArgumentException: Unknown color
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Unknown color
        at android.graphics.Color.parseColor(Color.java:1400)
        at com.reactnative.ivpusic.imagepicker.PickerModule.configureCropperColors(PickerModule.java:606)

**Comment by quyenlt1812** [comment]
It only supports hex color. Try to convert you rgb color to hex
P/S: #ffc8c8

**Comment by ObidosDev** [comment]
@quyenlt1812 I have wrote about this at the issue itself, BUT this is not clear from doc
