### ISSUE TITLE
安装了新版后podfile直接不能安装了

### ISSUE THREAD

**Issue by ikimiler** [ivpusic/react-native-image-crop-picker#1280]
删掉这个插件是好的，请问怎么解决

[!] Invalid `Podfile` file: 767: unexpected token at 'Error: Non-whitespace before first tag.

Line: 0

Column: 1

Char: 

    at error (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/sax/lib/sax.js:651:10)

    at strictFail (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/sax/lib/sax.js:677:7)

    at beginWhiteSpace (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/sax/lib/sax.js:951:7)

    at SAXParser.write (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/sax/lib/sax.js:1006:11)

    at new XmlDocument (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/xmldoc/lib/xmldoc.js:261:15)

    at readManifest (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:10)

    at Object.projectConfig (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/@react-native-community/cli-platform-android/build/config/index.js:59:46)

    at Object.get project [as project] (/Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/index.js:114:50)

    at /Users/kimi/Desktop/works/axd-app/axd_react_native_app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:8:452

    at Array.forEach (<anonymous>)

 #  from /Users/kimi/Desktop/works/axd-app/axd_react_native_app/ios/Podfile:53
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  end
 #  -------------------------------------------

`

**Comment by ivpusic** [comment]
have to close this issue because it looks like not related to this module
