### ISSUE TITLE
The App fails to open the camera on Android 10

### ISSUE THREAD

**Issue by camilo5972** [ivpusic/react-native-image-crop-picker#1296]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.31.1
- react-native v0.62.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

When calling the openCamera function the device must open the camera to take a photo. In versions less than Android 10 it works correctly

### Actual behaviour

The application fails and closes

### Attachments

// stacktrace or any other useful debug info

2020-05-28 11:59:03.087 1848-5924/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 10231665 , only wrote 10231619
    
    --------- beginning of system
2020-05-28 11:59:03.098 2094-4555/system_process I/ActivityTaskManager: START u0 {act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list U:content://com.everis.covid19.contacttracing.provider/external_files/Android/data/com.everis.covid19.contacttracing/files/Pictures/image-773252c0-ffe9-4e08-8161-92e1e465a97d3109887371223342888.jpg} (has extras)} from uid 10135
2020-05-28 11:59:03.119 2094-4555/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.119 2094-4555/system_process I/chatty: uid=1000(system) Binder:2094_11 identical 18 lines
2020-05-28 11:59:03.119 2094-4555/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.128 1859-1899/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3936256
2020-05-28 11:59:03.158 1841-1841/? D/Zygote: Forked child process 15302
2020-05-28 11:59:03.160 2094-2124/system_process I/ActivityManager: Start proc 15302:com.android.camera2/u0a124 for activity {com.android.camera2/com.android.camera.CaptureActivity}
2020-05-28 11:59:03.169 15302-15302/? W/android.camera: Unexpected CPU variant for X86 using defaults: x86_64
2020-05-28 11:59:03.194 2094-4555/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.196 2094-4555/system_process I/chatty: uid=1000(system) Binder:2094_11 identical 28 lines
2020-05-28 11:59:03.196 2094-4555/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.199 2094-2118/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.200 2094-2118/system_process I/chatty: uid=1000(system) android.anim identical 18 lines
2020-05-28 11:59:03.200 2094-2118/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.209 15302-15302/? D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
2020-05-28 11:59:03.209 15302-15302/? D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.manager-V1.0-java.jar
2020-05-28 11:59:03.209 15302-15302/? D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
2020-05-28 11:59:03.211 15302-15302/? I/android.camera: The ClassLoaderContext is a special shared library.
2020-05-28 11:59:03.215 15302-15302/? I/android.camera: The ClassLoaderContext is a special shared library.
2020-05-28 11:59:03.225 15302-15302/? V/CAM_Profiler: [  0.000ms][ui] GUARD: CameraApp onCreate() - START
2020-05-28 11:59:03.225 15302-15302/? V/CAM_Profiler: [  0.000ms][ui] GUARD: FirstRunDetector getTimeOfFirstRun - START
2020-05-28 11:59:03.226 15302-15302/? V/CAM_Profiler: [  0.858ms][ui] GUARD: FirstRunDetector getTimeOfFirstRun - [ 0.858ms] PreferenceManager.getDefaultSharedPreferences
2020-05-28 11:59:03.228 15302-15302/? V/CAM_Profiler: [  2.316ms][ui] GUARD: FirstRunDetector getTimeOfFirstRun - [ 1.458ms] preferences.getLong
2020-05-28 11:59:03.228 15302-15302/? V/CAM_Profiler: [  2.407ms][ui] GUARD: FirstRunDetector getTimeOfFirstRun - STOP
2020-05-28 11:59:03.228 15302-15302/? V/CAM_Profiler: [  3.032ms][ui] GUARD: CameraApp onCreate() - [ 3.032ms] initializeTimeOfFirstRun
2020-05-28 11:59:03.228 15302-15302/? V/CAM_Profiler: [  3.126ms][ui] GUARD: CameraApp onCreate() - [ 0.094ms] UsageStatistics.initialize
2020-05-28 11:59:03.228 15302-15302/? V/CAM_Profiler: [  3.534ms][ui] GUARD: CameraApp onCreate() - [ 0.408ms] clearNotifications
2020-05-28 11:59:03.228 15302-15302/? V/CAM_Profiler: [  3.534ms][ui] GUARD: CameraApp onCreate() - STOP
2020-05-28 11:59:03.239 1911-2136/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2020-05-28 11:59:03.240 1911-2136/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2020-05-28 11:59:03.241 15302-15302/? V/CAM_QuickActivity: START onCreate: Activity = com.android.camera.CaptureActivity@e5cc694
2020-05-28 11:59:03.242 15302-15302/? V/CAM_Profiler: [  0.000ms][ui] GUARD: CameraActivity.onCreateTasks - START
2020-05-28 11:59:03.243 15302-15302/? D/CAM_LocationManager: Using LegacyLocationProvider
2020-05-28 11:59:03.246 15302-15302/? D/CAM_MemoryManagerImpl: Max native memory: 358 MB
2020-05-28 11:59:03.237 15302-15302/? W/RenderThread: type=1400 audit(0.0:62): avc: denied { write } for name="property_service" dev="tmpfs" ino=8319 scontext=u:r:untrusted_app_27:s0:c124,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.android.camera2
2020-05-28 11:59:03.249 15302-15331/? D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
2020-05-28 11:59:03.249 15302-15302/? I/CAM_OneCamFtrCnfgCrtr: CaptureModule? true
2020-05-28 11:59:03.249 15302-15331/? W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
2020-05-28 11:59:03.263 15302-15302/? V/CAM_Profiler: [ 21.514ms][ui] GUARD: CameraActivity.onCreateTasks - [12.951ms] Glide.setup
2020-05-28 11:59:03.265 15302-15302/? D/CAM_Camera2OneCamMgr: Getting First BACK Camera
2020-05-28 11:59:03.266 15302-15302/? I/CameraManagerGlobal: Connecting to camera service
2020-05-28 11:59:03.271 15302-15331/? D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
2020-05-28 11:59:03.275 15302-15302/? D/CAM_Camera2OneCamMgr: Getting First FRONT Camera
2020-05-28 11:59:03.275 15302-15331/? D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
2020-05-28 11:59:03.277 15302-15302/? W/CAM_Camera2OneCamMgr: No front-facing camera found.
2020-05-28 11:59:03.281 15302-15302/? D/AndroidRuntime: Shutting down VM
2020-05-28 11:59:03.281 15302-15331/? D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
    
    --------- beginning of crash
2020-05-28 11:59:03.282 15302-15302/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.camera2, PID: 15302
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.camera2/com.android.camera.CaptureActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:461)
        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findCameraId(Camera2OneCameraManagerImpl.java:148)
        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findFirstCameraFacing(Camera2OneCameraManagerImpl.java:114)
        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.<init>(Camera2OneCameraManagerImpl.java:78)
        at com.android.camera.one.v2.Camera2OneCameraManagerImpl.create(Camera2OneCameraManagerImpl.java:61)
        at com.android.camera.one.OneCameraModule.provideOneCameraManager(OneCameraModule.java:68)
        at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1473)
        at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-05-28 11:59:03.284 2094-6994/system_process W/ActivityTaskManager:   Force finishing activity com.android.camera2/com.android.camera.CaptureActivity
2020-05-28 11:59:03.284 2094-6994/system_process W/InputReader: Device has associated, but no associated display id.
2020-05-28 11:59:03.285 2094-15335/system_process I/DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
2020-05-28 11:59:03.285 2094-6994/system_process W/ActivityTaskManager:   Force finishing activity com.everis.covid19.contacttracing/.MainActivity
2020-05-28 11:59:03.289 2094-2123/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver

**Comment by mjm918** [comment]
I'm facing the same issue.. Any update on this?

**Comment by ppritesh** [comment]
any solution for this issue ?

**Comment by desaiparv5** [comment]
having the same issue. Did you solve it?

**Comment by mjm918** [comment]
> having the same issue. Did you solve it?

yes..i uninstalled it and stopped using the library

**Comment by itvignes09** [comment]
Then What is the alternate library you used? @mjm918

**Comment by ivpusic** [comment]
try version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.35.0

**Comment by fxricky** [comment]
> try version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.35.0

need to upgrade the gradle version to use the latest update or else will have this error
`error: unexpected element <queries> found in <manifest>`

**Comment by TheTimeWalker** [comment]
Just to add to this: To upgrade you need to go to android/app/build.gradle and change the version for `com.android.tools.build:gradle`. If you're on the latest RN 0.63.2 that would mean changing 3.5.3 to at least 3.5.4
