### ISSUE TITLE
App Crash [Android]

### ISSUE THREAD

**Issue by srfaytkn** [ivpusic/react-native-image-crop-picker#1360]
### Version
- react-native-image-crop-picker v0.32.2
- react-native v0.63.2

### Platform
- Android

### Expected behaviour
- opening photo cropping screen

### Actual behaviour
- application crash

### Steps to reproduce

1. Call  ImagePicker.openPicker({ includeBase64: true, cropping: true });

2. Select photo from gallery

3. Crash

### Attachments

- Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(159694848bytes) bitmap.
       at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
       at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
       at com.yalantis.ucrop.util.FastBitmapDrawable.draw(FastBitmapDrawable.java:41)
       at android.widget.ImageView.onDraw(ImageView.java:1532)
       at android.view.View.draw(View.java:21618)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.updateDisplayListIfDirty(View.java:20474)
       at android.view.View.draw(View.java:21350)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4446)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4205)
       at android.view.View.draw(View.java:21621)
       at com.android.internal.policy.DecorView.draw(DecorView.java:964)
       at android.view.View.updateDisplayListIfDirty(View.java:20483)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:584)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:590)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:668)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3840)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3648)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2954)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:875)
       at android.view.Choreographer.doFrame(Choreographer.java:776)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by KDederichs** [comment]
Can confirm the same with RN 0.62.2.
It's not always crashing the app though, it appears that it only happens when the user selects an image that is too large in resolution/file size.

**Comment by lironsher** [comment]
I have the same with 0.63.2 which was not in version 0.62.2.

the user selects the image and the cropper is crushing - returning to the app with no result

**Comment by amdrade** [comment]
Same with RN 0.62.2

**Comment by dimpleshusband** [comment]
getting the same issue with larger pictures, any idea on how to resolve this or a temp fix?

**Comment by changweining** [comment]
getting the same issue with larger pictures, any idea on how to resolve this or a temp fix?

**Comment by KDederichs** [comment]
For people looking into this:
Seems to be in issue in the UCrop library used to build this.
There's been a fix around for this (https://github.com/Yalantis/uCrop/pull/662) which seems to work as far as I can tell.
Now how to get this into your react native package:
Fork UCrop, apply the fix yourself and push it to GitHub.
Then get https://www.npmjs.com/package/patch-package , navigate through your node modules to `react-native-image-crop-picker`
In there open up the `/android/build.gradle` file and replace `implementation 'com.github.yalantis:ucrop:2.2.5-native'` with `implementation 'com.github.YOUR_GITHUB_NAME:ucrop:master-SNAPSHOT'` (this will cause it to use your repository with the fix instead of the official one.
create the patch by running` yarn/npm patch-package eact-native-image-crop-picker`, clear the android build and you should be good to go

**Comment by KDederichs** [comment]
Another update on this, they fixed the code in uCrop so I made a PR with the updated dependency

**Comment by ivpusic** [comment]
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.33.0

**Comment by Kunalpaul12** [comment]
What help me 

```
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
    extraPackagerArgs: [ '--minify=false' ]
]
```

put this on top of the index.js

import 'react-native-gesture-handler';
