### ISSUE TITLE
Could not invoke ImageCropPicker.openPicker error when Android app doesn't have `WRITE_EXTERNAL_STORAGE` permission

### ISSUE THREAD

**Issue by IjzerenHein** [ivpusic/react-native-image-crop-picker#159]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.7
- react-native v0.39

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

When the Android permission `WRITE_EXTERNAL_STORAGE` is not in the AndroidManifest.xml, the image-picker should not try to access it, nor crash.

### Actual behaviour

App crashes (see attached screenshot) when invoking either `ImagePicker.openPicker` or `ImagePicker.openCamera`, when app doesn't have the `WRITE_EXTERNAL_STORAGE` permission.

### Steps to reproduce

1. Remove android permission from AndroidManifest.xml (e.g. using `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />`

2. Call `ImagePicker.openPicker`

```js
async onSelectPhoto() {
		try {
			const image = await ImagePicker.openPicker({
				width: 400,
				height: 400,
				cropping: true
			});
```

### Attachments

![image](https://cloud.githubusercontent.com/assets/6184593/20933460/62399246-bbd8-11e6-9f55-06c362fc7b58.png)

// stacktrace or any other useful debug info

```
12-06 17:19:19.194 20499-20499/com.atogear.arion D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
12-06 17:19:19.314 20499-20773/com.atogear.arion E/unknown:React: Exception in native call
                                                                  java.lang.RuntimeException: Could not invoke ImageCropPicker.openPicker
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:332)
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                      at java.lang.Thread.run(Thread.java:818) 
                                                                   Caused by: java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar:classes2.dex)
                                                                      at com.facebook.react.ReactActivityDelegate.requestPermissions(ReactActivityDelegate.java:177)
                                                                      at com.facebook.react.ReactActivity.requestPermissions(ReactActivity.java:109)
                                                                      at com.reactnative.ivpusic.imagepicker.PickerModule.permissionsCheck(PickerModule.java:206)
                                                                      at com.reactnative.ivpusic.imagepicker.PickerModule.openPicker(PickerModule.java:331)
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318) 
                                                                      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                      at java.lang.Thread.run(Thread.java:818) 
12-06 17:19:19.324 20499-20499/com.atogear.arion D/AbsListView: Get MotionRecognitionManager
12-06 17:19:19.624 20499-20499/com.atogear.arion W/unknown:React: Calling JS function after bridge has been destroyed.
12-06 17:19:19.624 20499-20619/com.atogear.arion W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.atogear.arion/cache
12-06 17:19:21.114 20499-20499/com.atogear.arion W/unknown:React: Calling JS function after bridge has been destroyed.
```

**Comment by ivpusic** [comment]
Thanks for pointing to this. I added missing permission to library manifest, so now should be always there. For camera permission users should add it if needed (https://github.com/ivpusic/react-native-image-crop-picker#android). Released here https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.10.8

**Comment by IjzerenHein** [comment]
Hi! I'm afraid that doesn't solve the problem. I don't want to be forced to need that permission in my app at all. What if someone only needs to use the Camera? In that case the app shouldn't require that permission. Currently, the app crashes when using either `ImagePicker.openPicker` or `ImagePicker.openCamera`, when the permission is missing. 

What is the reason for needing that permission? I think we should prevent the app from crashing if that permission is missing though.

Cheers

**Comment by ivpusic** [comment]
Writing to external storage is permission required in all cases. Taking image with camera will touch storage in the end, and it will throw exception on android 6 if permission is not granted.

**Comment by IjzerenHein** [comment]
Right I see, thanks for explaining!

As for the camera, isn't the reason that the camera feature writes to external-storage because of this function?

```js
private File createImageFile() throws IOException {
        String imageFileName = "image-" + UUID.randomUUID().toString();
        File path = Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_PICTURES);
        File image = File.createTempFile(imageFileName, ".jpg", path);

        // Save a file: path for use with ACTION_VIEW intents
        mCurrentPhotoPath = "file:" + image.getAbsolutePath();

        return image;
    }
```

Here it explicitly chooses a file on external storage..

What would you think of making this configurable? Like being able to specify the base-folder in which the camera file is generated?

**Comment by ivpusic** [comment]
Hm, this could be an option, but then still ucrop (library for cropping images) will ask for write permission. Of course if you are not using cropping when selecting images from camera you won't get this issue, but in the end to cover all these cases sounds like a lot of if/else + additional configuration.

**Comment by IjzerenHein** [comment]
Hmm I see. That would indeed still be a problem yeah. I had no idea that having external storage was such a hard dependency for camera and picture operations..
Right, I'm gonna think about it some more. Maybe just have to convince my users that external storage permissions are a hard requirement.

Thanks for the help, really appreciate it. And this library is awesome! Awesome work you did, thanks so much!

**Comment by trackwell-mike** [comment]
Hi - I wanted to check in on this older issue to see if there have been any updates to Android requiring both permissions (openCamera and openPicker) for this library to work. We would prefer to only require camera access. Thanks!
