### ISSUE TITLE
Running example in Android simulator fails

### ISSUE THREAD

**Issue by daniel** [ivpusic/react-native-image-crop-picker#1686]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.37.2

### Platform

- Android

### Expected behaviour

The app starts in the Android emulator

### Actual behaviour

The build fails

### Steps to reproduce

1. `cd example`

2. `yarn install`

3. `yarn android`

### Attachments

```
example[ master]$ yarn android
yarn run v1.22.17
$ node node_modules/react-native/local-cli/cli.js run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 2702 file(s) to forward-jetify. Using 16 workers...
info JS server already running.
info Installing the app...

> Configure project :app
WARNING: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported

> Task :app:stripDebugDebugSymbols UP-TO-DATE
WARNING: Compatible side by side NDK version was not found. Default is 21.0.6113669.
Compatible side by side NDK version was not found. Default is 21.0.6113669.

> Task :app:installDebug FAILED
Skipping device 'Pixel_4_API_31(AVD) - 12' for 'app:debug': Could not find build of variant which supports density -1 and an ABI in x86_64, arm64-v8a
59 actionable tasks: 2 executed, 57 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

    at makeError (/Users/daniel/projects/_test/react-native-image-crop-picker/example/node_modules/execa/index.js:174:9)
    at /Users/daniel/projects/_test/react-native-image-crop-picker/example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/daniel/projects/_test/react-native-image-crop-picker/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/daniel/projects/_test/react-native-image-crop-picker/example/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
example[ master]$ 
```

**Comment by trostinsky** [comment]
Probably problem with your device, not with library
