### ISSUE TITLE
In Android 10 some user has this error java.lang.NullPointerException: uriString

### ISSUE THREAD

**Issue by tastafur** [ivpusic/react-native-image-crop-picker#1728]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.37.2
- react-native v0.66.3

### Platform
Tell us to which platform this issue is related

- iOS
- Android 10

### Expected behaviour

Open crop picker tool

### Actual behaviour
```
java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:496)
        at android.net.Uri$StringUri.<init>(Uri.java:486)
        at android.net.Uri.parse(Uri.java:458)
        at com.reactnative.ivpusic.imagepicker.PickerModule.openCropper(PickerModule.java:421)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

### Steps to reproduce

Sometimes some users the crop picker tool does not open in android 10 due to this error

**Comment by mojtabaasadi** [comment]
I am facing same problem on android 10 and 11

**Comment by sspeng123** [comment]
same ..
FATAL EXCEPTION: mqt_native_modules
    Process: , PID: 8910
    java.lang.NullPointerException: uriString
        at android.net.Uri$StringUri.<init>(Uri.java:496)
        at android.net.Uri$StringUri.<init>(Uri.java:486)
        at android.net.Uri.parse(Uri.java:458)
        at com.reactnative.ivpusic.imagepicker.PickerModule.openCropper

**Comment by mojtabaasadi** [comment]
I found out that problem is in my code when calling open cropper, it was
getting called with empty path

**Comment by sspeng123** [comment]
thanks, I ready fixed
ImagePicker.openCropper({
    path: resp.sourceURL || resp.path,
    includeBase64: true,
})

**Comment by mojtabaasadi** [comment]
@sspeng123 great, you can close this issue now, I think.
