### ISSUE TITLE
Image picker not wokring

### ISSUE THREAD

**Issue by navneetccna** [ivpusic/react-native-image-crop-picker#177]
### Version
Tell us which versions you are using: 
- "react-native-image-crop-picker": "^0.10.9"
- "react-native": "^0.23.0",

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
Open image picker

import ImagePicker from 'react-native-image-crop-picker';
ImagePicker.openPicker({
		  width: 300,
		  height: 400,
		  cropping: true
		}).then(image => {
		  console.log(image);
		});

### Actual behaviour
Error : undefined is not an object (evaluating '_reactNativeImageCropPicker2.default.openPicker')

I also tested in the android studio and getting this error 

Error:(31, 39) error: cannot find symbol class PermissionAwareActivity
Error:(32, 39) error: cannot find symbol class PermissionListener
Error:(47, 1) error: PickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
Error:(208, 143) error: cannot find symbol class PermissionListener
Error:(208, 15) error: cannot find symbol class PermissionAwareActivity
Error:(585, 5) error: method does not override or implement a method from a supertype
Error:(596, 5) error: method does not override or implement a method from a supertype
Error:Execution failed for task ':react-native-image-crop-picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by ivpusic** [comment]
it seems that you did not install it correctly. Please follow all steps from here https://github.com/ivpusic/react-native-image-crop-picker#install

**Comment by navneetccna** [comment]
I followed all the steps even i tried again and again multiple times but same issue

**Comment by navneetccna** [comment]
Last installation log is 

npm WARN react-native-image-crop-picker@0.10.9 requires a peer of react-native@>=0.33.0 but none was installed.
npm WARN react-native-pulse-loader@1.0.2 requires a peer of react-native@^0.27 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
The library is already present in android/settings.gradle.
The library is already present in android/app/build.gradle.
Next step: add the library to your MainActivity.java by calling addPackage().
Look for the package name in node_modules/react-native-image-crop-picker/android/src/main/java

**Comment by ivpusic** [comment]
these are old installation instructions for android, but they are still valid. https://github.com/ivpusic/react-native-image-crop-picker/blob/79d3dab7e5dd377551701a74203deb5667bdfde2/README.md#android-1.

Please follow them and verify that all steps are completed. Probably `link` is not fully completed.

**Comment by navneetccna** [comment]
i tried every thins still same issue

:react-native-image-crop-picker:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:31: error: cannot find symbol
import com.facebook.react.modules.core.PermissionAwareActivity;
                                      ^
  symbol:   class PermissionAwareActivity
  location: package com.facebook.react.modules.core
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:32: error: cannot find symbol
import com.facebook.react.modules.core.PermissionListener;
                                      ^
  symbol:   class PermissionListener
  location: package com.facebook.react.modules.core
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:47: error: PickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:207: error: cannot find symbol
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
                                                                                                                                              ^
  symbol:   class PermissionListener
  location: class PickerModule
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:207: error: cannot find symbol
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
              ^
  symbol:   class PermissionAwareActivity
  location: class PickerModule
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:623: error: method does not override or implement a method from a supertype
    @Override
    ^
D:\nav\GSOPS\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java:634: error: method does not override or implement a method from a supertype
    @Override
    ^
7 errors
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.898 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:10128) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined

**Comment by TigerC10** [comment]
@navneetccna did you solve this issue?  I'm experiencing the same thing.

@ivpusic It's been linked correctly.
```shell
> react-native link react-native-image-crop-picker
(node:66108) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
rnpm-install info Android module react-native-image-crop-picker is already linked 
rnpm-install info iOS module react-native-image-crop-picker is already linked 
```


```shell
> ./gradlew clean :react-native-image-crop-picker:compileDebugJavaWithJavac --stacktrace
# ...
# ...
# ...
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:31: error: cannot find symbol
import com.facebook.react.modules.core.PermissionAwareActivity;
                                      ^
  symbol:   class PermissionAwareActivity
  location: package com.facebook.react.modules.core
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:32: error: cannot find symbol
import com.facebook.react.modules.core.PermissionListener;
                                      ^
  symbol:   class PermissionListener
  location: package com.facebook.react.modules.core
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:47: error: PickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:208: error: cannot find symbol
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
                                                                                                                                              ^
  symbol:   class PermissionListener
  location: class PickerModule
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:208: error: cannot find symbol
            ((PermissionAwareActivity) activity).requestPermissions(missingPermissions.toArray(new String[missingPermissions.size()]), 1, new PermissionListener() {
              ^
  symbol:   class PermissionAwareActivity
  location: class PickerModule
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:585: error: method does not override or implement a method from a supertype
    @Override
    ^
../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:596: error: method does not override or implement a method from a supertype
    @Override
    ^
7 errors
:react-native-image-crop-picker:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-image-crop-picker:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:47)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:38)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:127)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more


BUILD FAILED

Total time: 11.973 secs
```

Debug output isn't much more helpful.

**Comment by navneetccna** [comment]
@TigerC10 update your react-native or use the old version of this plugin.

In my case i checked that the  com.facebook.react.modules.core.PermissionAwareActivity was not exist in my react native plugin so i updated the same and it worked for me.

**Comment by TigerC10** [comment]
Okay, identified the issue.  The build.gradle lists:

```gradle
compile "com.facebook.react:react-native:+"
```

However, Facebook no longer publishes the `react-native` artifact on [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.facebook.react%22%20AND%20a%3A%22react-native%22).  Their last update was 0.20.1 on 15-Feb-2016.

Needed to alter the build.gradle for `react-native-image-crop-picker` to reference the node_modules directory for the maven repo.

**Comment by jarandmi** [comment]
@TigerC10 I got the same problem. Why is this something that don't effects everyone and how did you fix it? 

"react-native-image-crop-picker": "^0.12.4",
"react-native": "^0.42.0-rc.1"

**Comment by TigerC10** [comment]
@jarandmi - See PR #245 for the changes I made to this project in my `node_modules` dir for the fix.  Basically, the maven dependency lists the latest version of `com.facebook.react:react-native` which in maven central is an outdated version of react-native (`0.20.1`).  Gotta make it look in the node_modules dir for the latest version instead.

**Comment by booboothefool** [comment]
@TigerC10 So based on what your saying, this is something that can suddenly happen after some period of time? My project was working for a few months, now suddenly won't build. It's cause facebook stopped publishing react-native to maven or whatever?

Do I still need to do anything fancy if I just want to run:
react-native 0.37
react-native-image-crop-picker @ 0.11.2
?
