### ISSUE TITLE
Take picture make the app crush.

### ISSUE THREAD

**Issue by DonRyu** [ivpusic/react-native-image-crop-picker#1842]
### Version
Tell us which versions you are using: 

"react-native-image-crop-picker": "v0.36.2",
"react-native": "0.68.2",

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour

when do ImagePicker.openCamera( ), app never get crushed

### Actual behaviour

Whenever I press the button to do the ImagePicker.openCamera( ), app get crush

### Steps to reproduce

Explanation about the error

FATAL EXCEPTION: main

Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.

FATAL EXCEPTION: main
Process: com.minwon_admin_app, PID: 12833
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.minwon_admin_app/com.minwon_admin_app.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenStackFragment: calling Fragment constructor caused an exception
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
	at com.minwon_admin_app.MainActivity.onCreate(MainActivity.java:23)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 27 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
	at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:53)
	at com.swmansion.rnscreens.ScreenStackFragment.<init>(ScreenStackFragment.kt:35)
	... 30 more

**Comment by subhadeepquantiantech** [comment]
+1

**Comment by chingakhamronald** [comment]
Same here

**Comment by karan-nagarro** [comment]
Facing Same issue in redmi note 9 pro

**Comment by pnthach95** [comment]
This error was caused by react native screens, not related to image crop picker. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to fix it.

**Comment by karan-nagarro** [comment]
@pnthach95 after implementing this solutio getting same issue.

**Comment by pnthach95** [comment]
> @pnthach95 after implementing this solution getting same issue.

- Are you sure you have exactly same log as OP (with the link to react-native-screens#17 solution)? If yes, this is the only solution for this issue.
- Do you clean project before run?
- If you use bootsplash, have you changed `super.onCreate(savedInstanceState)` to `super.onCreate(null)` in `protected void onCreate` as document said?

**Comment by karan-nagarro** [comment]
@pnthach95 
yes, added oncreate method solution share by you in mainActivity of project.

**Comment by pnthach95** [comment]
> @pnthach95 yes, added oncreate method solution share by you in mainActivity of project.

You are out of luck then. It fixed my apps on Samsung phones, not test on any Redmi phones. Follow that thread to find the best solution for your issue.

image-crop-picker is one of many ways to active this bug since the root of bug is on rn-screens and it appears randomly. Sometimes, you open app, press home, do some heavy tasks or leave it overnight, then reopen app and it crashes immediately, like 4 times in a row. This is the bug.

**Comment by VijaykumarWBD** [comment]
@DonRyu @karan-nagarro  Did find any work arounds? I too have similar issue.

**Comment by VijaykumarWBD** [comment]
https://github.com/ivpusic/react-native-image-crop-picker/issues/1798#issuecomment-1188375421

**Comment by CodingWithNobody** [comment]
Check this https://www.youtube.com/watch?v=Bx_gwRODtlY
