### ISSUE TITLE
Video Capture for Android 13 (SDK 33) doesn't work

### ISSUE THREAD

**Issue by DaneHoward** [ivpusic/react-native-image-crop-picker#1859]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.38.1
- react-native v0.66.5

### Platform
- Android

### Expected behaviour
Videos are captured successfully on openCamera with mediaType option 'video' 

### Actual behaviour
When capturing a video on Android SDK 33 / Android 13 -> The only response is that the user cancelled even if that's not the case

### Steps to reproduce

1. Init project

2. Install react-native-image-crop-picker

3. Try to capture video on an Android 13 (SDK 33) device

4. Only response on RN side is "Error: User cancelled image selection" 

5. Response in Android emulator is attached below

### Additional Info
I wanted to add this section because I've already done some research and hope that helps

1. A  similar issue with openPicker was solved by permissions outlined here:  [https://issuetracker.google.com/issues/237634019?pli=1](https://issuetracker.google.com/issues/237634019?pli=1) and here [https://github.com/ivpusic/react-native-image-crop-picker/issues/1849](https://github.com/ivpusic/react-native-image-crop-picker/issues/1849)
2. Google warns of different permissions needed for Android 13 Video Recording: [https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions)
3. RN offers PermissionsAndroid but when I tried to request the the READ_MEDIA_VIDEO the app would crash and say the permission is null. Could be my own lack of understanding but those same permissions are in the Manifest file so not sure why I was getting that null.

### Attachments

// stacktrace or any other useful debug info
I get this bad boy in the Android Emulator:

```
FATAL EXCEPTION: main
                                                                                                    Process: com.android.camera2, PID: 2576
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.ContentValues.put(java.lang.String, java.lang.Long)' on a null object reference
                                                                                                    	at com.android.camera.VideoModule.saveVideo(VideoModule.java:1263)
                                                                                                    	at com.android.camera.VideoModule.stopVideoRecording(VideoModule.java:1513)
                                                                                                    	at com.android.camera.VideoModule.onStopVideoRecording(VideoModule.java:656)
                                                                                                    	at com.android.camera.VideoModule.onShutterButtonClick(VideoModule.java:697)
                                                                                                    	at com.android.camera.ShutterButton.performClick(ShutterButton.java:190)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29335)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by huanguolin** [comment]
I face the same issue. 
Capture video is work, but the `resultCode` is `RESULT_CANCELED`(in `onActivityResult`). If I ignore the `resultCode`, the later steps all execute correctly (I can get the video, do the upload, etc.).

It's strange...

**Comment by huanguolin** [comment]
I found that the reason why it causes the result to be "Error: User cancelled image selection" is because the confirmation screen (see the screenshot below) is missing after clicking end recording.

I use a local android project (without react-native, pure native) and test the "same" code to come out with this screen, so there is no problem.

I tried adjusting the react-native version, the android os version and android sdk version and found that only react-native + android 13 devices have this problem (regardless of react-native version and android sdk version).

But I still don't know how to fix this issue ....

![Screenshot_20221118_102823](https://user-images.githubusercontent.com/12430413/202596648-6d1a19e2-c387-4a13-8583-63b730468f1c.png)

**Comment by jde8aa** [comment]
I encountered the same error when trying to do video capture on an Android emulator that was using Android 13, but when I created a test build and put it on a real device both the image and video capturing worked correctly.

Currently using version 0.37.3 of react-native-image-crop-picker and version 0.68.5 of RN.

**Comment by DaneHoward** [comment]
@huanguolin  @jde8aa  @Talhafayyaz11  Hi friends! I will mark this issue as resolved but first, let me help ya out!

So, I'm going to take a stab that all 3 of you are using Android 13+ which is giving the "didCancel" response. 

This is not an issue with the image picker (well, the docs could be clearer)

This is a PERMISSION ISSUE!

The fix should look like this:

`import {
    ...
    PermissionsAndroid,
    Platform,
  } from 'react-native';
`
Then in your component:

`  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        title: "Cool Photo App Camera Permission",
        message:
          "Cool Photo App needs access to your camera " +
          "so you can take awesome pictures.",
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      return true;
    } else {
      return false;
    }
  } catch (err) {
    console.warn(err);
    return false;
  }`

This should fix up any Android 13 Video capture issues related to didCancel. Since at least the 4 of us have had this issue (and I assume more) They should make more of a stink about it in the docs but the code works.

**Comment by CodingWithNobody** [comment]
Check this https://www.youtube.com/watch?v=Bx_gwRODtlY
