### ISSUE TITLE
App crashed when selecting video - Android |  java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by rahuljeevan-experion** [ivpusic/react-native-image-crop-picker#1862]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.38.1
- react-native v0.69.3

### Platform

- Android

### Expected behaviour

Selecting a video from files should return the selected video path and other details.

### Actual behaviour

 The app is getting crashes when selecting large video files

### Attachments

> Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 431897344 byte allocation with 10793613 free bytes and 245MB until OOM, target footprint 21587229, growth limit 268435456
       at com.reactnative.ivpusic.imagepicker.PickerModule.createExternalStoragePrivateFile(PickerModule.java:627)
       at com.reactnative.ivpusic.imagepicker.PickerModule.resolveRealPath(PickerModule.java:602)
       at com.reactnative.ivpusic.imagepicker.PickerModule.getAsyncSelection(PickerModule.java:496)
       at com.reactnative.ivpusic.imagepicker.PickerModule.imagePickerResult(PickerModule.java:802)
       at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:877)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:339)
       at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:824)
       at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:133)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
       at android.app.Activity.dispatchActivityResult(Activity.java:8659)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5939)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by RAIERIN** [comment]
@rahuljeevan-experion did you find any solution?

**Comment by rahuljeevan-experion** [comment]
@RAIERIN nope

**Comment by psbdgr8** [comment]
> @RAIERIN nope

any solution or another module?

**Comment by Dipak-Complitech** [comment]
any solution for that I having same issue Please help or any another package suggest ?

**Comment by GeeksEra** [comment]
@Dipak-Complitech  https://github.com/ivpusic/react-native-image-crop-picker/pull/2137
