### ISSUE TITLE
Android 13: App crashes after selecting image

### ISSUE THREAD

**Issue by VijaykumarWBD** [ivpusic/react-native-image-crop-picker#1910]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v~0.39.0
- react-native v0.68.3

### Platform

Android 13 Google pixel 6a, Samsung devices

### Expected behaviour

Open the camera(openCamera) and click Image. After clicking Image, a Tick mark appears. After clicking the Tick mark. The app should not crash and continue to provide a response.
Open Upload from the device (openPicker) and select the image. The app should not crash and continue to provide a response.

### Actual behaviour

Open the camera(openCamera) and click Image. After clicking Image, a Tick mark appears. After clicking the Tick mark. App crashes.
Open Upload from the device (openPicker) and select the image. App crashes

### Steps to reproduce

As mentioned above.

### Attachments

I see the following error message on the android studio logcat.

FATAL EXCEPTION: main 
```
Process: com.dev, PID: 17608
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/MenuHost;
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1339)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.MenuHost" on path: DexPathList[[zip file "/data/app/~~OWNy8JtSuoSXF1xLRZTXhA==/com.dev-devgeezq64sbiRRr8DuE3A==/base.apk"],nativeLibraryDirectories=[/data/app/~~OWNy8JtSuoSXF1xLRZTXhA==/com.dev-z7HgeezdevsdevRr8DuE3A==/lib/arm64, /data/app/~~OWNy8JtSuoSXF1xLRZTXhA==/com..dev-z7Hgeezq64sbiRRr8dev3dev/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.Class.newInstance(Native Method) 
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1339) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```
                                                                                                    

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by VijaykumarWBD** [comment]
When looking at logcat I noticed that the issue was caused by java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.MenuHost".

It turns out that my build.gradle file was forcing androidx.core to 1.6.0 and that was the reason of the resolution issue. I changed:

```
configurations.all {
   resolutionStrategy { force 'androidx.core:core:1.6.0' }
}
```

to:

```
configurations.all {
   resolutionStrategy { force 'androidx.core:core:1.7.0' }
}
```

And it worked flawlessly.
