### ISSUE TITLE
Android App Not Responding com.reactnative.ivpusic.imagepicker.PickerModule.resolveRealPath

### ISSUE THREAD

**Issue by ariefrhmn** [ivpusic/react-native-image-crop-picker#2036]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.38.0
- react-native v0.72.10

### Platform
Tell us to which platform this issue is related
- Android
- Samsung Galaxy A24
- Android 14

### Actual behaviour
Application got `ANR triggered by slow IO operations `

### Attachments
`main (native):tid=1 systid=30753 
#00 pc 0xecf18 libc.so (__openat + 8) (BuildId: 59cafcd8c6514064584f920f18ea8760)
#01 pc 0xa0c0c libc.so (__open_2 + 76) (BuildId: 59cafcd8c6514064584f920f18ea8760)
#02 pc 0xa2c98 libc.so (realpath + 56) (BuildId: 59cafcd8c6514064584f920f18ea8760)
#03 pc 0x21ed0 libopenjdk.so (canonicalize + 176) (BuildId: fc4c0ac2dde70b1afe348b962a85a634)
#04 pc 0x2533c libopenjdk.so (Java_java_io_UnixFileSystem_canonicalize0 + 104) (BuildId: fc4c0ac2dde70b1afe348b962a85a634)
       at java.io.UnixFileSystem.canonicalize0(Native method)
       at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:185)
       at java.io.File.getCanonicalPath(File.java:611)
       at java.io.File.getCanonicalFile(File.java:636)
       at java.io.File.mkdirs(File.java:1355)
       at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:3778)
       at android.app.ContextImpl.getExternalFilesDirs(ContextImpl.java:901)
       at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:890)
       at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:315)
       at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:315)
       at com.reactnative.ivpusic.imagepicker.PickerModule.resolveRealPath(PickerModule.java:594)
       at com.reactnative.ivpusic.imagepicker.PickerModule.getAsyncSelection(PickerModule.java:496)
       at com.reactnative.ivpusic.imagepicker.PickerModule.imagePickerResult(PickerModule.java:783)
       at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:877)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:375)
       at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:822)
       at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:107)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:136)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
       at android.app.Activity.dispatchActivityResult(Activity.java:9324)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:6055)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:6101)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

// stacktrace or any other useful debug info
<img width="1110" alt="Screenshot 2024-03-22 at 13 12 21" src="https://github.com/ivpusic/react-native-image-crop-picker/assets/27661894/b3f4b76a-5482-45b7-bf59-b66234c09f02">

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by atultiwaree** [comment]
Any solution ??

**Comment by jronnen** [comment]
We were facing a similar issue, it appears that since android 14 this error started appearing.  We were able to fix it by removing the compression attribute from the  `ImagePicker.openPicker`

If makes me wonder why this is all happening on a UI thread and not a background thread.  I couldn't repo the issue in android 13 but android 14+ I can.
