### ISSUE TITLE
Android crop crash

### ISSUE THREAD

**Issue by kiliwalk** [ivpusic/react-native-image-crop-picker#22]
on android emulator 4.4.4 
```
E/VdcInflateDelegate( 1797): Exception while inflating <vector>
E/VdcInflateDelegate( 1797): org.xmlpull.v1.XmlPullParserException: Binary XML file line #1<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate( 1797): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
E/VdcInflateDelegate( 1797): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
E/VdcInflateDelegate( 1797): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:878)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:355)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:49)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:65)
E/VdcInflateDelegate( 1797): 	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
E/VdcInflateDelegate( 1797): 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)
E/VdcInflateDelegate( 1797): 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
E/VdcInflateDelegate( 1797): 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
E/VdcInflateDelegate( 1797): 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
E/VdcInflateDelegate( 1797): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
E/VdcInflateDelegate( 1797): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/VdcInflateDelegate( 1797): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/VdcInflateDelegate( 1797): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/VdcInflateDelegate( 1797): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/VdcInflateDelegate( 1797): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/VdcInflateDelegate( 1797): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
E/VdcInflateDelegate( 1797): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
E/VdcInflateDelegate( 1797): 	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:102)
E/VdcInflateDelegate( 1797): 	at android.app.Activity.performCreate(Activity.java:5231)
E/VdcInflateDelegate( 1797): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/VdcInflateDelegate( 1797): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/VdcInflateDelegate( 1797): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/VdcInflateDelegate( 1797): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/VdcInflateDelegate( 1797): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/VdcInflateDelegate( 1797): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate( 1797): 	at android.os.Looper.loop(Looper.java:136)
E/VdcInflateDelegate( 1797): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/VdcInflateDelegate( 1797): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate( 1797): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate( 1797): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/VdcInflateDelegate( 1797): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/VdcInflateDelegate( 1797): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kiliwalk** [comment]
Fixed by using gradle 2+

**Comment by sunnyyants** [comment]
I am facing the exactly the same problem, how to specifically use gradle 2+? Thanks

**Comment by kiliwalk** [comment]
Change the file `android/build.gradle` with `com.android.tools.build:gradle:2+`

**Comment by sunnyyants** [comment]
Thanks!
