### ISSUE TITLE
Failure delivering result ResultInfo : Illegal callback invocation from native module. This callback type only permits a single invocation from native code

### ISSUE THREAD

**Issue by the-simian** [ivpusic/react-native-image-crop-picker#235]
### Version
- react-native-image-crop-picker v0.12.2
- react-native v0.41.2
- react v15.4.2

### Platform
- Android

### Trace
```sh
java.lang.RuntimeException Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {com.seejanego/com.seejanego.MainActivity}: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    ActivityThread.java:4925 android.app.ActivityThread.deliverResults
    ActivityThread.java:4968 android.app.ActivityThread.handleSendResult
    ActivityThread.java:222 android.app.ActivityThread.access$1600
    ActivityThread.java:1849 android.app.ActivityThread$H.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:158 android.os.Looper.loop
    ActivityThread.java:7229 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:1230 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1120 com.android.internal.os.ZygoteInit.main


Caused: java.lang.RuntimeException Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    CallbackImpl.java:32 com.facebook.react.bridge.CallbackImpl.invoke
    PromiseImpl.java:70 com.facebook.react.bridge.PromiseImpl.reject
    PromiseImpl.java:38 com.facebook.react.bridge.PromiseImpl.reject
    ResultCollector.java:65 com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem
    PickerModule.java:619 com.reactnative.ivpusic.imagepicker.PickerModule.croppingResult
    PickerModule.java:630 com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult
    ReactContext.java:261 com.facebook.react.bridge.ReactContext.onActivityResult
    XReactInstanceManagerImpl.java:627 com.facebook.react.XReactInstanceManagerImpl.onActivityResult
    ReactActivityDelegate.java:149 com.facebook.react.ReactActivityDelegate.onActivityResult
    ReactActivity.java:77 com.facebook.react.ReactActivity.onActivityResult
    Activity.java:7137 android.app.Activity.dispatchActivityResult
    ActivityThread.java:4921 android.app.ActivityThread.deliverResults
    ActivityThread.java:4968 android.app.ActivityThread.handleSendResult
    ActivityThread.java:222 android.app.ActivityThread.access$1600
    ActivityThread.java:1849 android.app.ActivityThread$H.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:158 android.os.Looper.loop
    ActivityThread.java:7229 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:1230 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1120 com.android.internal.os.ZygoteInit.main
```

### About

We've only seen this twice, and it was in our issue tracker. I can't say for sure exactly what conditions caused this bug to occur. I mainly wanted to log this to see if anyone else had seen it, or if you might have some insight as to what might cause it. I'll try to fill in any more details you might need. I've not been able to repro this myself

**Comment by ivpusic** [comment]
synchronized  is missing on this line https://github.com/ivpusic/react-native-image-crop-picker/blob/c03895ca8e26c9e6830e86331811b4d15215dc42/android/src/main/java/com/reactnative/ivpusic/imagepicker/ResultCollector.java#L69. Could you send PR? Thanks

**Comment by the-simian** [comment]
No problem, I'll submit a PR this evening

**Comment by the-simian** [comment]
@ivpusic I've done as you asked in #237 

I haven't had a chance to test this thoroughly, but this seems to be correct. Can you also take a look?

**Comment by ivpusic** [comment]
looks good, thanks

**Comment by birgernass** [comment]
### Version
* react-native-image-crop-picker 0.15.1
* react-native 0.46.4
* react 16.0.0-alpha.12

### Platform
* Android 7.0

### Device
* Model VKY-L09 (HUAWEIVKY-L09)

### Message
```
Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {de.******.app/de.******.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference
```

### Trace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference
    at com.reactnative.ivpusic.imagepicker.PickerModule.croppingResult(PickerModule.java:670)
    at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:681)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:256)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:601)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
    at android.app.Activity.dispatchActivityResult(Activity.java:7188)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4334)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4381)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6577)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {de.tellonym.app/de.tellonym.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4338)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4381)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6577)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

### About
This error occurs for one of our users, when he presses the check icon after cropping an image.
