### ISSUE TITLE
Android - Crash after selecting image (Fix included)

### ISSUE THREAD

**Issue by sfratini** [ivpusic/react-native-image-crop-picker#256]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.12.4
- react-native v0.41.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
Image gets chosen

### Actual behaviour
App implodes and catches fire 

### Steps to reproduce

1. Use ImagePicker.OpenPicker

2.Choose image and select

3.Crash

### Attachments
`03-02 21:36:25.300 557-557/com.mpact E/VdcInflateDelegate: Exception while inflating <vector>
                                                           org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
                                                               at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:541)
                                                               at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:478)
                                                               at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:441)
                                                               at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:736)
                                                               at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:359)
                                                               at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:189)
                                                               at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
                                                               at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
                                                               at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
                                                               at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                               at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                               at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                               at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                               at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                               at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
                                                               at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
                                                               at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
                                                               at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                               at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
                                                               at android.app.Activity.performCreate(Activity.java:5008)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                               at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                               at dalvik.system.NativeStart.main(Native Method)
03-02 21:36:25.300 557-557/com.mpact W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa627f288)
03-02 21:36:25.300 557-557/com.mpact E/AndroidRuntime: FATAL EXCEPTION: main
                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mpact/com.yalantis.ucrop.UCropActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                           at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                           at android.os.Looper.loop(Looper.java:137)
                                                           at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                           at dalvik.system.NativeStart.main(Native Method)
                                                        Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
                                                           at android.content.res.Resources.loadDrawable(Resources.java:1918)
                                                           at android.content.res.Resources.getDrawable(Resources.java:659)
                                                           at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194)
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
                                                           at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
                                                           at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                           at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                           at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                           at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                           at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                           at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
                                                           at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
                                                           at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
                                                           at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                           at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
                                                           at android.app.Activity.performCreate(Activity.java:5008)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                           at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                           at android.os.Looper.loop(Looper.java:137) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                           at dalvik.system.NativeStart.main(Native Method) 
                                                        Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                           at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
                                                           at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
                                                           at android.content.res.Resources.loadDrawable(Resources.java:1915)
                                                           at android.content.res.Resources.getDrawable(Resources.java:659) 
                                                           at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346) 
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194) 
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182) 
                                                           at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717) 
                                                           at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187) 
                                                           at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77) 
                                                           at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127) 
                                                           at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147) 
                                                           at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27) 
                                                           at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50) 
                                                           at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201) 
                                                           at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181) 
                                                           at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521) 
                                                           at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                           at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106) `

Hot to fix:
1) Make sure you are using gradle 2.2.x:

        classpath 'com.android.tools.build:gradle:2.2.3'

2) Add this in your app gradle:

android {
...
    defaultConfig {
       ...
        vectorDrawables.useSupportLibrary true
       ...
    }

I would add a PR but I would hate to break something else

**Comment by ivpusic** [comment]
thanks! similar issue and solution here https://github.com/ivpusic/react-native-image-crop-picker/issues/214. I will add it to readme file.
