### ISSUE TITLE
Install broke my project

### ISSUE THREAD

**Issue by sidferreira** [ivpusic/react-native-image-crop-picker#360]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14.0
- react-native v0.42.3

### Platform
Mac

### Steps to reproduce

1. npm install -g ignite-cli 

2. ignite new PizzaApp

3. cd PizzaApp

4. npm i react-native-image-crop-picker

### Attachments

```
npm i react-native-image-crop-picker --save
npm WARN gentlyRm not removing /Volumes/External/Dev/ValeFotosProj/app/node_modules/.bin/jest as it wasn't installed by /Volumes/External/Dev/ValeFotosProj/app/node_modules/jest-cli

> husky@0.13.4 uninstall /Volumes/External/Dev/ValeFotosProj/app/node_modules/husky
> node ./bin/uninstall.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'strip-ansi'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/External/Dev/ValeFotosProj/app/node_modules/chalk/index.js:4:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm WARN lifecycle husky@0.13.4~uninstall: continuing anyway husky@0.13.4 uninstall: `node ./bin/uninstall.js`
npm WARN lifecycle Exit status 1
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native-image-crop-picker@0.14.0 requires a peer of react-native@>=0.40.0 but none was installed.

+ react-native-image-crop-picker@0.14.0
added 1 package and removed 864 packages in 78.493s
```

**Comment by ivpusic** [comment]
I cannot reproduce this.

**Comment by sidferreira** [comment]
@ivpusic Sorry wasting your time. I later found out that NPM was removing items from my install by it's own will. I'm closing this issue.
