### ISSUE TITLE
[Android] Taking and saving pictures fails

### ISSUE THREAD

**Issue by dtmzr** [ivpusic/react-native-image-crop-picker#378]
### Version
- react-native-image-crop-picker v0.14.1
- react-native v0.45.1

### Platform
- Android

### Expected behaviour
Picking or taking one image, cropping it and saving it's path to redux which is combined with redux-persist.

### Actual behaviour
Picking one image and cropping works fine.
Whenever I want to take a picture and crop it the app 'resets/reloads' after cropping and runs out of memory.

### More infos
- Not using base64
- Config and log in attachments
- Debugging on S4 (GT-l9505) Android: 5.0.1
- Will test it for different versions (emulator)
- Sometimes I see the screen rotating... couldn't that be a cause? (RN still got a lot of issues with rotation)
- #240 similar issue
- Disabling cropping doesn't affect the issue at all

### Steps to reproduce
1. use ImagePicker.openCamera()
2. Take picture and save
3. Crop and confirm

### Attachments
```javascript
{
  cropperActiveWidgetColor: '#91B6FF',
  cropperCircleOverlay: true,
  cropperStatusBarColor: '#91B6FF',
  cropperToolbarColor: '#91B6FF',
  cropping: true,
  height: 300,
  hideBottomControls: true,
  loadingLabelText: 'Verarbeite Daten...',
  mediaType: 'photo',
  showCropGuidelines: false,
  showsSelectedCount: false,
  smartAlbums: ['UserLibrary', 'PhotoStream'],
  width: 300,
}
```

> 07-17 13:38:07.312 7139-7249/com.testapp I/BitmapCropTask: Should crop: true
07-17 13:38:07.312 7139-7249/com.testapp D/uCrop JNI: Crop image with CImg
07-17 13:38:07.332 7139-7139/com.testapp I/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices
07-17 13:38:10.975 7139-7139/com.testapp D/Activity: performCreate Call secproduct feature valuefalse
07-17 13:38:10.975 7139-7139/com.testapp D/Activity: performCreate Call debug elastic valuetrue
07-17 13:38:10.985 7139-7139/com.testapp D/image-crop-picker: Skipping image compression
07-17 13:38:10.995 7139-7139/com.testapp D/SensorManager: registerListener :: 0, K330 3-axis Accelerometer, 66667, 0,  
07-17 13:38:10.995 7139-7288/com.testapp W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
07-17 13:38:10.995 7139-7303/com.testapp W/unknown:PackagerConnectionSettings: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
07-17 13:38:11.156 7139-7139/com.testapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@37231ab0 time:172336074
07-17 13:38:12.857 7139-7161/com.testapp I/art: Background sticky concurrent mark sweep GC freed 32975(3MB) AllocSpace objects, 6(96KB) LOS objects, 6% free, 54MB/58MB, paused 9.246ms total 116.851ms
07-17 13:38:15.139 7139-7161/com.testapp I/art: Background partial concurrent mark sweep GC freed 34704(4MB) AllocSpace objects, 7(19MB) LOS objects, 31% free, 34MB/50MB, paused 9.918ms total 228.149ms
07-17 13:38:22.747 7139-12158/com.testapp W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
07-17 13:38:22.757 7139-12158/com.testapp E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
07-17 13:38:22.757 7139-12158/com.testapp E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                Process: com.testapp, PID: 7139
                                                                java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                    at java.lang.Thread.nativeCreate(Native Method)
                                                                    at java.lang.Thread.start(Thread.java:1063)
                                                                    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
                                                                    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1338)
                                                                    at okhttp3.ConnectionPool.put(ConnectionPool.java:135)
                                                                    at okhttp3.OkHttpClient$1.put(OkHttpClient.java:149)
                                                                    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:188)
                                                                    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                    at okhttp3.RealCall.access$100(RealCall.java:33)
                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:818)
07-17 13:38:22.817 7139-7139/com.testapp D/SensorManager: unregisterListener ::   
07-17 13:38:22.917 7139-11507/com.testapp W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
07-17 13:38:22.917 7139-11507/com.testapp E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
07-17 13:38:22.927 7139-11508/com.testapp W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
07-17 13:38:22.927 7139-11508/com.testapp E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
07-17 13:38:22.927 7139-11508/com.testapp W/libc: pthread_create failed: couldn't allocate 1064960-byte stack: Out of memory
07-17 13:38:22.927 7139-11508/com.testapp E/art: Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again"
07-17 13:38:22.927 7139-11508/com.testapp I/Process: Sending signal. PID: 7139 SIG: 9

Ps. I'm 600m away from your companies location, any time up for fixing this together!

**Comment by ivpusic** [comment]
thanks for reporting this. I see OutOfMemoryError error. Would be cool if you have some time to check if we can somehow avoid OutOfMemoryError.

**Comment by marlti7** [comment]
in andorid, need use localpath to save picture

**Comment by DenizTemizer** [comment]
@marlti7 sorry for the late response but what do you mean by that?
Like I said picking images works fine in android, it only crashes when I try to  take a picture first.

**Comment by dgurns** [comment]
I'm also getting this issue -- app restarts after taking picture. However choosing image from library works fine.

**Comment by sabbyt54** [comment]
+1

**Comment by sandropoluan** [comment]
+1. 
App restarts after taking picture but works fine when picking image.

**Comment by kwes01** [comment]
I have this problem when I take a photo from the camera
![imagen](https://user-images.githubusercontent.com/17342168/35534391-9e5a3cfc-04fd-11e8-96a9-963a8ee949a9.png)

this is my function

openCamera() {
    ImagePicker.openCamera({
      width: 300,
      height: 300,
      cropping: true,
      cropperCircleOverlay: true,
      compressImageMaxWidth: 640,
      compressImageMaxHeight: 480,
      compressImageQuality: 0.5,
      compressVideoPreset: 'MediumQuality',
      includeExif: true,
    })
      .then((image) => {
        console.log('received image', image);
        this.setState({
          profilePciture: {
            uri: image.path,
            width: image.width,
            height: image.height,
            mime: image.mime,
          },
        });
      })
      .catch((e) => {
        console.log(e);
        Alert.alert(e.message ? e.message : e);
      });
  }

**Comment by arifinoid** [comment]
Same here, this issue still occurs on low device android

**Comment by akhilsanker** [comment]
Hi,
Facing the issue.

@adnkh @arifinoid 
Any workaround found?

Thanks

**Comment by b3hz4d** [comment]
> I have this problem when I take a photo from the camera
> ![imagen](https://user-images.githubusercontent.com/17342168/35534391-9e5a3cfc-04fd-11e8-96a9-963a8ee949a9.png)
> 
> this is my function
> 
> openCamera() {
> ImagePicker.openCamera({
> width: 300,
> height: 300,
> cropping: true,
> cropperCircleOverlay: true,
> compressImageMaxWidth: 640,
> compressImageMaxHeight: 480,
> compressImageQuality: 0.5,
> compressVideoPreset: 'MediumQuality',
> includeExif: true,
> })
> .then((image) => {
> console.log('received image', image);
> this.setState({
> profilePciture: {
> uri: image.path,
> width: image.width,
> height: image.height,
> mime: image.mime,
> },
> });
> })
> .catch((e) => {
> console.log(e);
> Alert.alert(e.message ? e.message : e);
> });
> }

This issue is not solved after 3 years yet !!!!
