### ISSUE TITLE
[Android] Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by birgernass** [ivpusic/react-native-image-crop-picker#415]
### Version
* react-native-image-crop-picker 0.15.1
* react-native 0.46.4
* react 16.0.0-alpha.12

### Platforms
* Android 7.0
* Android 7.1.1

### Devices
* Huawei P10 Plus
* Samsung Galaxy S7
* OnePlus 5

### Message
```
Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {de.******.app/de.******.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference
```

### Trace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference
    at com.reactnative.ivpusic.imagepicker.PickerModule.croppingResult(PickerModule.java:670)
    at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:681)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:256)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:601)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
    at android.app.Activity.dispatchActivityResult(Activity.java:7188)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4334)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4381)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6577)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {de.tellonym.app/de.tellonym.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(java.lang.String, java.lang.String)' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4338)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4381)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6577)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

### About
This error occurs for one of our users, when he presses the check icon after cropping an image.

**Edit:** The Error occurs sometimes after cropping. For some users every time. Especially, after pressing the cancel button. We also encountered app freezes after canceling on iOS.

**Comment by hsxiaochou** [comment]
I have same  problem...

**Comment by hsxiaochou** [comment]
solved this problem  : Make sure you are using Gradle 2.2.x (project build.gradle)

**Comment by birgernass** [comment]
We are already using Gradle 2.2.3

**Comment by Jobeso** [comment]
@hsxiaochou We are running on Gradle 2.2.3 but still get the problem on some devices. Have you done anything beside that to fix it?

**Comment by maspay** [comment]
i've problem here too. the problem occurs when used startResolutionForResult on LocationServices

**Comment by murzhang** [comment]
hi,please check your code of MainActivity.java,if has onActivityResult,then throw this error.

**Comment by Jobeso** [comment]
@murzhang Thanks for your suggestion. Sadly it is not working for us. When building I get the error `error: cannot find symbol if(this.onActivityResultStatus>0) {`

**Comment by jjdp** [comment]
+1 on a Samsung SM-N9005 Android 5.0

**Comment by ivpusic** [comment]
should be fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.20.3
