### ISSUE TITLE
Android - Calling openPicker Sends App to Background; Pointer to function is lost

### ISSUE THREAD

**Issue by wkoutre** [ivpusic/react-native-image-crop-picker#447]
EDIT: I realize this is a common issue, especially with Android 7.0+. This is a dupe issue of the one over at [react-native-image-picker](https://github.com/react-community/react-native-image-picker/issues/471).

Having one open here, though, may increase visability. Feel free to close if you don't feel the same, though.

### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.16.1
- react-native v0.48.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

App's `App_State` doesn't change; image is able to be chosen and cropped.

### Actual behaviour

- `App_State` changes to `BACKGROUND` on `ImagePicker.openPicker`
- function is lost
- `App_State` changes to `FOREGROUND` when image is chosen

iOS does not have this issue of changing the `App_State` to choose an image.

### Steps to reproduce

```
handleChoosePic = ({ index }) => {
        const options = {
            cropping: true,
            height: Math.round(WIDTH / houseHeightDivideByRatio * 2),
            width: Math.round(WIDTH * 2),
            loadingLabelText: "",
            mediaType: "photo"
        };
    
    ImagePicker.openPicker(options)
      .then(response => {
        console.log("RESPONSE", response);
        const { path: uri } = response;
        this.props.editHousePics({ uri, index });
        this.setHasEdited(index);
      })
      .catch(err => console.log("error", err));
  };
```

1. onPress, this function is called (with an index of the picture being chosen/changed in the current screen's gallery)

2. `ImagePicker.openPicker(options)` is run

3. `App_State` changes to `background`

4. Image is selected, but no cropping prompt appears; returns back into app

5. `ImagePicker.openPicker(options)` call is lost; `App_State` changes to `foreground`

### Attachments

// stacktrace or any other useful debug info

```09-15 18:27:36.494  1632  1644 I ActivityManager: START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from uid 10077 on display 0
09-15 18:27:36.513  1632  1778 I ActivityManager: START u0 {act=android.intent.action.GET_CONTENT typ=image/* flg=0x3000000 cmp=com.android.documentsui/.DocumentsActivity (has extras)} from uid 10077 on display 0
09-15 18:27:36.587  3070  3536 D EGL_emulation: eglMakeCurrent: 0xaa9e0c60: ver 2 0 (tinfo 0xac3c92f0)
09-15 18:27:36.622  1357  1687 W audio_hw_generic: Not supplying enough data to HAL, expected position 20371618 , only wrote 20234532
09-15 18:27:36.633  1632  1651 I ActivityManager: Displayed com.android.documentsui/.DocumentsActivity: +112ms (total +131ms)
09-15 18:27:36.635  3070  3537 D Documents: userMode=0, userSortOrder=0 --> mode=2, sortOrder=2
09-15 18:27:36.636  3070  3537 W Documents: Failed to query
09-15 18:27:36.636  3070  3537 W Documents: android.os.OperationCanceledException: The operation has been canceled.
09-15 18:27:36.636  3070  3537 W Documents: 	at android.os.CancellationSignal.throwIfCanceled(CancellationSignal.java:54)
09-15 18:27:36.636  3070  3537 W Documents: 	at android.content.ContentProviderClient.query(ContentProviderClient.java:132)
09-15 18:27:36.636  3070  3537 W Documents: 	at com.android.documentsui.DirectoryLoader.loadInBackground(DirectoryLoader.java:167)
09-15 18:27:36.636  3070  3537 W Documents: 	at com.android.documentsui.DirectoryLoader.loadInBackground(DirectoryLoader.java:94)
09-15 18:27:36.636  3070  3537 W Documents: 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
09-15 18:27:36.636  3070  3537 W Documents: 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
09-15 18:27:36.636  3070  3537 W Documents: 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
09-15 18:27:36.636  3070  3537 W Documents: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-15 18:27:36.636  3070  3537 W Documents: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-15 18:27:36.636  3070  3537 W Documents: 	at com.android.documentsui.ProviderExecutor.run(ProviderExecutor.java:107)
09-15 18:27:36.637  3070  3537 D Documents: userMode=0, userSortOrder=0 --> mode=2, sortOrder=2
09-15 18:27:36.647  7746  7805 D EGL_emulation: eglMakeCurrent: 0xaa9e1260: ver 2 0 (tinfo 0xaaacc4e0)
09-15 18:27:36.649  7746  7805 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb40bdb60
09-15 18:27:39.823  3070  3070 D Documents: onFinished() [content://com.android.providers.media.documents/document/image%3A63]
09-15 18:27:39.872  7746  7805 D EGL_emulation: eglMakeCurrent: 0xaa9e1260: ver 2 0 (tinfo 0xaaacc4e0)
09-15 18:27:39.998  3070  3536 D EGL_emulation: eglMakeCurrent: 0xaa9e0c60: ver 2 0 (tinfo 0xac3c92f0)
09-15 18:27:39.998  3070  3536 E Surface : getSlotFromBufferLocked: unknown buffer: 0xb40bc300
09-15 18:27:40.000  3070  3536 D OpenGLRenderer: endAllStagingAnimators on 0xa1ef6880 (GridView) with handle 0xa1d05ad0
09-15 18:27:40.248  3070  3070 I art     : Starting a blocking GC Explicit
09-15 18:27:40.251  3070  3070 I art     : Explicit concurrent mark sweep GC freed 3703(216KB) AllocSpace objects, 0(0B) LOS objects, 22% free, 7MB/9MB, paused 56us total 3.328ms
09-15 18:27:40.256  3070  3070 I art     : Starting a blocking GC Explicit
09-15 18:27:40.260  3070  3070 I art     : Explicit concurrent mark sweep GC freed 6277(467KB) AllocSpace objects, 5(300KB) LOS objects, 24% free, 6MB/8MB, paused 52us total 3.467ms
09-15 18:27:40.260  3070  3070 I art     : Starting a blocking GC Explicit
09-15 18:27:40.263  3070  3070 I art     : Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 24% free, 6MB/8MB, paused 51us total 2.532ms
09-15 18:27:42.996  1357  1687 W audio_hw_generic: Not supplying enough data to HAL, expected position 20511725 , only wrote 20374003
09-15 18:27:49.857  7746  7903 W unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry```

**Comment by bsonntag** [comment]
Is there any workaround for this?

**Comment by wkoutre** [comment]
Looking into it further today with the project I'm working on. I haven't done much Android development, but I started looking into ImagePickerModule.java.

I quickly found my issue -- line 600: `if (activity instanceof ReactActivity)` ...

I actually had to change my app's `MainActivity.java` to extend a custom Activity. Once I changed it, this image picker immediately worked. So, since I need to extend the custom Activity, my solution is to add `if (activity instanceof ReactActivity || activity instanceof CustomActivity)`...

**Comment by wkoutre** [comment]
Of course, it turns out it's not that simple.

But I'm 100% sure the CustomActivity is the culprit via trial & error and comparing the logs for an image-selection flow.

**Comment by VincentRong** [comment]
@wkoutre Hi，I encounter the similar problem of yours. And I found your comment of ImagePickerModule.java is about project react-native-image-picker. So have you used the 'react-native-image-picker' instead of 'react-native-image-corp-picker' ?

**Comment by wkoutre** [comment]
@VincentRong I've tried both, yes. My last comment did reference `react-native-image-picker` -- sorry about that -- but the issue was the same for both `react-native-image-picker` and `react-native-image-crop-picker` if I extended a custom Activity in my project's `MainActivity.java` file, rather than extending `ReactActivity`.

**Comment by VincentRong** [comment]
@wkoutre Yeah, I think the problem I encountered is about this reason. But I have to extend a NativeActivity, I can not find how to modify the .java code in the project react-native-image-crop-picker. I will appreciate that if you know about this.

**Comment by wkoutre** [comment]
Off the top of my head, I'm not sure.

But I'd start by opening the app in a development environment, using the logger in Android Studio or `adb logcat` via the terminal, and filtering the logs for what's happening when you call `ImageCropPicker.openPicker`

**Comment by wkoutre** [comment]
Somewhere inside node_modules >> react-native-image-crop-picker >> android >> src >> main >> java >> com >> reactnative >> ivpusic >> imagepicker >>  PickerModule.java

**Comment by krewllobster** [comment]
@wkoutre I know its been a lonnnnng time since you posted this, but did you find a solution? This issue is still around and I'm currently experiencing it, but only when trying to accept an image from the camera. As soon as you click the check to indicate that you are selecting the picture you just snapped, the entire app just flat out restarts.

**Comment by VicEsquivel** [comment]
@krewllobster same here. Ive tried what it says  [here](https://github.com/react-native-community/react-native-image-picker/issues/471#issuecomment-481710241) that in the release builds it does not happen anymore, but no... That didnt work either.

Did you find a solution?
