### ISSUE TITLE
hi,on Android it will be crash when selected pic.

### ISSUE THREAD

**Issue by yangjingshuai** [ivpusic/react-native-image-crop-picker#501]
at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
  at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
  at android.os.Looper.loop(Looper.java:135)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
  at java.lang.Thread.run(Thread.java:818)

**Comment by ivpusic** [comment]
can you please provide more information? from this stacktrace I cannot help you

**Comment by WhoJave** [comment]
@yangjingshuai  have u solved this crash ?
