### ISSUE TITLE
crashed in android API 24 / OS version 7.0 

### ISSUE THREAD

**Issue by sarangan** [ivpusic/react-native-image-crop-picker#509]
### Version
- react-native-image-crop-picker@0.17.3
- react-native-cli: 2.0.1
- react-native: 0.45.1

### Platform
device :- HUAWEI MHA-L29

- Android
OS version 7.0 24
API 24

### Expected behaviour
should load the image cropper

### Actual behaviour
app crashed when it loads the ImagePicker.openCropper function.  lower than android api 7.0 works fine. 

```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: sg.com.sara.snap, PID: 15648
                                                   com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `double'
                                                       at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
                                                       at com.reactnative.ivpusic.imagepicker.PickerModule.setConfiguration(PickerModule.java:117)
                                                       at com.reactnative.ivpusic.imagepicker.PickerModule.openCropper(PickerModule.java:369)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.cxxbridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:761)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:199)
                                                       at java.lang.Thread.run(Thread.java:776)
```

**Comment by ivpusic** [comment]
do you have some time to debug this?

**Comment by sarangan** [comment]
Hi, I just added parseInt on width and height then it works fine. I guess some android devices screen width came up with decimal numbers ? 

```
 ImagePicker.openCropper({
       path: this.state.imagePath,
       width: parseInt(SCREENWIDTH -30),
       height: parseInt(SCREENWIDTH - 30)
     }).then(image => {
```

**Comment by ivpusic** [comment]
yes, int should be provided

**Comment by Vishal7591** [comment]
Can you please help me, in my android crash. 

ImagePicker.openCropper({
        freeStyleCropEnabled: true,
        path: avatar.path,
        width: 150,
        height: 150,
        cropping: true
      }).then(image => {
        console.log(image);
        };

I am even providing the integer values to the height and width
