### ISSUE TITLE
ImageCropPicker.openPicker got 4 arguments, expected 3

### ISSUE THREAD

**Issue by qmegas** [ivpusic/react-native-image-crop-picker#559]
Hi, I got following error when trying to call `openPicker` function.

### Version
- react-native-image-crop-picker v0.19.1
- react-native v0.46.4

### Platform
Android

### Error
```
Exception in native call
com.facebook.react.bridge.NativeArgumentsParseException: ImageCropPicker.openPicker got 4 arguments, expected 3
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:344)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:154)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
at java.lang.Thread.run(Thread.java:762)
```

### Code
```JS
ImageCropPicker.openPicker({
   width: 400,
   height: 400,
   cropping: true,
}, image => {
   console.log('>>> image - ', image);
});
```

**Comment by qmegas** [comment]
Ok, found the problem. Wrong function call. Should call it like that:
```JS
ImageCropPicker.openPicker({
   width: 400,
   height: 400,
   cropping: true,
}).then(image => {
   console.log('>>> image - ', image);
});
```
