### ISSUE TITLE
Android 4.4 throws an exception after opening a photo album to select a picture

### ISSUE THREAD

**Issue by JasonX829** [ivpusic/react-native-image-crop-picker#575]
android studio Error log

E/TransformImageView: onFailure: setImageUri
                                                                           java.io.FileNotFoundException: No such file or directory
                                                                               at android.os.Parcel.openFileDescriptor(Native Method)
                                                                               at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:252)
                                                                               at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:198)
                                                                               at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:953)
                                                                               at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:815)
                                                                               at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:770)
                                                                               at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:97)
                                                                               at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at java.lang.Thread.run(Thread.java:841)

**Comment by ivpusic** [comment]
do you have some time to investigate?
