### ISSUE TITLE
crash app when click confirm with android version 4.2.2

### ISSUE THREAD

**Issue by userbq201** [ivpusic/react-native-image-crop-picker#730]
stack trace

```
AndroidRuntime(17837): java.lang.NoClassDefFoundError: android.provider.DocumentsContract
E/AndroidRuntime(17837): 	at com.reactnative.ivpusic.imagepicker.RealPathUtil.getRealPathFromURI(RealPathUtil.java:23)
E/AndroidRuntime(17837): 	at com.reactnative.ivpusic.imagepicker.PickerModule.resolveRealPath(PickerModule.java:506)
E/AndroidRuntime(17837): 	at com.reactnative.ivpusic.imagepicker.PickerModule.getSelection(PickerModule.java:426)
E/AndroidRuntime(17837): 	at com.reactnative.ivpusic.imagepicker.PickerModule.cameraPickerResult(PickerModule.java:681)
E/AndroidRuntime(17837): 	at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:715)
E/AndroidRuntime(17837): 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
E/AndroidRuntime(17837): 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:692)
E/AndroidRuntime(17837): 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:126)
E/AndroidRuntime(17837): 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
E/AndroidRuntime(17837): 	at android.app.Activity.dispatchActivityResult(Activity.java:5311)
E/AndroidRuntime(17837): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3550)
E/AndroidRuntime(17837): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3597)
E/AndroidRuntime(17837): 	at android.app.ActivityThread.access$1100(ActivityThread.java:162)
E/AndroidRuntime(17837): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
E/AndroidRuntime(17837): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(17837): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(17837): 	at android.app.ActivityThread.main(ActivityThread.java:5400)
E/AndroidRuntime(17837): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17837): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(17837): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
E/AndroidRuntime(17837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
E/AndroidRuntime(17837): 	at dalvik.system.NativeStart.main(Native Method)
```

    "react-native": "0.55.3"
    "react-native-image-crop-picker": "^0.20.3"

**Comment by gvalentin** [comment]
android.provider.DocumentsContract was added in API level 19 (4.4).
https://developer.android.com/reference/android/provider/DocumentsContract

**Comment by userbq201** [comment]
@gvalentin api < 19 (4.2) not have DocumentsContract. And app crashed `java.lang.NoClassDefFoundError: android.provider.DocumentsContract`

**Comment by telmen** [comment]
any solution?
