### ISSUE TITLE
【iOS】run error: bundling failed: Error: While trying to resolve module `react-native-android-image-cropper` from file `Post_New_Dinner.js`, the package `/node_modules/react-native-android-image-cropper/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved 

### ISSUE THREAD

**Issue by 12343954** [ivpusic/react-native-image-crop-picker#832]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.2.4
- react-native v0.56.0

### Platform
Tell us to which platform this issue is related

- **iOS  is bad！**
- Android  is OK

### Actual behaviour
```
error: bundling failed: Error: While trying to resolve module `react-native-android-image-cropper` from file `/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/APP/View/Post_New_Dinner.js`, the package `/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/react-native-android-image-cropper/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/react-native-android-image-cropper/index`. Indeed, none of these files exist:

  * `/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/react-native-android-image-cropper/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/react-native-android-image-cropper/index/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:15)
    at DependencyGraph.resolveDependency (/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (native)
    at resolveDependencies (/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)
    at /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:467
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

```

**Comment by ivpusic** [comment]
looks like a problem with some other package called `react-native-android-image-cropper`. this one is called `react-native-image-crop-picker`.

**Comment by 12343954** [comment]
so sorry, I posted the wrong place !
