### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=0, data=null} to activity ... java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code

### ISSUE THREAD

**Issue by LuisRizo** [ivpusic/react-native-image-crop-picker#853]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.3
- react-native v0.55.4

### Platform
Tell us to which platform this issue is related

- [ ] iOS
- [x] Android

### Expected behaviour
Only one picker is opened and the app does not crash.

### Actual behaviour
Opens two Image Pickers and crashes the app.

### Steps to reproduce

1. Press the button that triggers the `ImagePicker.openPicker` function from the javascript multiple times very quickly.

2. Press Back button twice to go back to the original app from the Image Picker.

3. App crashes

### Attachments

Simple App to recreate the issue:
```
import React, { Component } from 'react';
import { View, Button } from 'react-native';
import ImagePicker from 'react-native-image-crop-picker'

class App extends Component {
    showPicker = () => {
        // Press Button Very Quickly to trigger Native Exception
        ImagePicker.openPicker({cropping: true}).then(res => console.log(res))
    }

    simulateQuickDoubleTap = () => {
        this.showPicker()
        this.showPicker()
    }


    render() {
        return (
            <View style={styles.container}>
                <Button
                    title="Tap Twice Quickly to Crash"
                    onPress={this.showPicker}
                />
                <Button
                    title="Simulate Quick Double Tap"
                    onPress={this.simulateQuickDoubleTap}
                />
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#2c3e50',
    },
});

export default App;
```

<details>
 <summary>Stack Trace</summary>

```
10-20 22:56:37.752 31459 31459 E AndroidRuntime: Process: com.reactnative.app, PID: 31459
10-20 22:56:37.752 31459 31459 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=0, data=null} to activity {com.reactnative.app/com.reactnative.app.MainActivity}: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: Caused by: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.bridge.PromiseImpl.reject(PromiseImpl.java:68)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.bridge.PromiseImpl.reject(PromiseImpl.java:36)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.reactnative.ivpusic.imagepicker.ResultCollector.notifyProblem(ResultCollector.java:65)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.reactnative.ivpusic.imagepicker.PickerModule.imagePickerResult(PickerModule.java:610)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.reactnative.ivpusic.imagepicker.PickerModule.onActivityResult(PickerModule.java:701)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:692)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:126)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at com.reactnative.app.MainActivity.onActivityResult(MainActivity.java:53)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7276)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
10-20 22:56:37.752 31459 31459 E AndroidRuntime: 	... 9 more
10-20 22:56:37.795  1631 30927 W ActivityManager:   Force finishing activity com.reactnative.app/com.reactnative.app.MainActivity
```

</details>

I know this is an edge case, but I'm creating this issue because it was marked as solved at #235 due to lack of reproduction steps.
Since I managed to figure out why it crashed, I thought I'd post it here to let the library developers be able to fix it for good.

A quick workaround is to disable the button that triggers the mutation once pressed using a state variable.

**Comment by RowgerGo** [comment]
I hava the same error.
react-native-image-crop-picker v0.21.1
react-native v0.51.0
```
FATAL EXCEPTION: main
                  Process: com.newenergy.fk, PID: 11937
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=-1, data=Intent 
```

**Comment by HosseinRashno** [comment]
Did you find the solution?

**Comment by FaggioniHQ** [comment]
I'm having this issue as well 

RN 0.60.4
image-crop-picker 0.25.0

**Comment by LuisRizo** [comment]
Not a permanent solution but as mentioned in the OP:

> A quick workaround is to disable the button that triggers the mutation once pressed using a state variable.
