### ISSUE TITLE
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=-1, data

### ISSUE THREAD

**Issue by RowgerGo** [ivpusic/react-native-image-crop-picker#879]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.1
- react-native v0.51.0

### Platform
Tell us to which platform this issue is related

- Android

1.select images,and cut it
 - error
```
W/libEGL: EGLNativeWindowType 0xcaad4008 disconnect failed
I/System.out: ---------------------------------------------requestCode61110
I/System.out: ---------------------------------------------requestCode为空
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.newenergy.fk, PID: 11937
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61110, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:560112 flg=0x1 }} to activity {com.newenergy.fk/com.newenergy.fk.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.reject(java.lang.String)' on a null object reference
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4932)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975)
                      at android.app.ActivityThread.-wrap20(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
                      at android.os.Handler.dispatchMessage(Handler.java:108)
                      at android.os.Looper.loop(Looper.java:166)
                      at android.app.ActivityThread.main(ActivityThread.java:7425)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)

```

### Attachments

// stacktrace or any other useful debug info

Love react-native-image-crop-picker? Please consider supporting our collective:
👉  https://opencollective.com/react-native-image-crop-picker/donate

**Comment by HosseinRashno** [comment]
Did you find the solution?

**Comment by FaggioniHQ** [comment]
Any news on this?. Still an issue on version 0.25.0.

RN 0.6.4

**Comment by FaggioniHQ** [comment]
I solved the issue. In my case, the is was related to custom integration intent that was badly resolved over onActivityResult method. Hope it helps.

**Comment by UnSensei** [comment]
@FaggioniHQ hey, could you please elaborate on your fix please?

**Comment by Hideiki** [comment]
+1 @FaggioniHQ
