### ISSUE TITLE
Tried to read an int, but got a non-integral double

### ISSUE THREAD

**Issue by AE0011** [ivpusic/react-native-image-crop-picker#889]
### Version
- react-native-image-crop-picker "^0.21.2"
- react-native "0.51.0"

### Platform
- Android 4.2.2 (just in release mode)
### Actual behaviour
fatal runtime error :
```
   com.facebook.react.bridge.UnexpectedNativeTypeException: Tried to read an int, but got a non-integral double: 600.938935
                                                       at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
                                                       at com.reactnative.ivpusic.imagepicker.PickerModule.setConfiguration(PickerModule.java:122)
                                                       at com.reactnative.ivpusic.imagepicker.PickerModule.openPicker(PickerModule.java:354)
```

### Steps to reproduce
```
 let w = parseInt(Number(screenW));
 let h = parseInt(Number((screenW * 250) / 400));
ImagePicker.openPicker({
                    compressImageMaxWidth: 640,
                    compressImageMaxHeight: 640,
                    width: w,
                    height: h,
                    cropping: true,
                    cropperCircleOverlay: false,
                    compressImageQuality: 0.5,
                    forceJpg: true,
                    //includeExif: true,
                    includeBase64: true,
                }).then(image => {
                }).catch(e => {
                });
```

**Comment by ivpusic** [comment]
```let w = parseInt(Number(screenW));
 let h = parseInt(Number((screenW * 250) / 400));```

this is the problem. w and h has to be integers.

**Comment by AE0011** [comment]
@ivpusic 
> w and h has to be integers.
As u see i change w , h to an integer.
```
 let w = parseInt(Number(screenW));
 let h = parseInt(Number((screenW * 250) / 400));
```

u mean js could not change it to int? (just in android 4.2.2 release mode!!)

**Comment by AE0011** [comment]
@ivpusic 
even after i change width and height to a constant value i got that error too!

```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.sss, PID: 32053
                                                   com.facebook.react.bridge.UnexpectedNativeTypeException: Tried to read an int, but got a non-integral double: 600.938935
                                                       at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
                                                       at com.reactnative.ivpusic.imagepicker.PickerModule.setConfiguration(PickerModule.java:122)
                                                       at com.reactnative.ivpusic.imagepicker.PickerModule.openPicker(PickerModule.java:354)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                       at java.lang.Thread.run(Thread.java:841)
```

```
 ImagePicker.openPicker({
                    compressImageMaxWidth: 640,
                    compressImageMaxHeight: 640,
                    width: 1000,
                    height: 625,
                    cropping: true,
                    cropperCircleOverlay: false,
                    compressImageQuality: 0.5,
                    forceJpg: true,
                    //includeExif: true,
                    includeBase64: true,
                })
```

**Comment by ivpusic** [comment]
weird. try updating to latest library version, it includes some fixes for default parameters

**Comment by AE0011** [comment]
updating didn't help! :(

**Comment by ivpusic** [comment]
could you try to debug setting configuration part in java file?
