### ISSUE TITLE
Cropping crashes the app

### ISSUE THREAD

**Issue by uforujjwal** [ivpusic/react-native-image-crop-picker#932]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.21.3
- react-native v0.5.2

### Platform

- Android

### Expected behaviour
When I try to upload picture gallery opens but as soon as I select any  picture from gallery the picture should open with option to crop it

### Actual behaviour
When I try to upload picture gallery opens but as soon as I select any  picture from gallery the app crashes (it works fine when cropping is set to false) 

### Steps to reproduce

const image = await ImagePicker.openPicker({
      mediaType: "photo",
      width: 60,
      height: 60,
      cropping: true,
      avoidEmptySpaceAroundImage: true,
      cropperCircleOverlay: true,
      compressImageMaxWidth: 60,
      compressImageMaxHeight: 60,
    });

1. Just open the gallery 

2.Select any picture from gallery

3.App will crash when cropping is set to true, works fine otherwise

### Attachments

// stacktrace 
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.facesandplacesui, PID: 19044
                  java.lang.NoSuchMethodError: No static method setFactory2(Landroid/view/LayoutInflater;Landroid/view/LayoutInflater$Factory2;)V in class Landroid/support/v4/view/LayoutInflaterCompat; or its super classes (declaration of 'android.support.v4.view.LayoutInflaterCompat' appears in /data/app/com.facesandplacesui-eGj4thqCbeld4AmeINsnjQ==/base.apk!classes4.dex)
                      at android.support.v7.app.AppCompatDelegateImplV9.installViewFactory(AppCompatDelegateImplV9.java:1071)
                      at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                      at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:113)
                      at android.app.Activity.performCreate(Activity.java:7136)
                      at android.app.Activity.performCreate(Activity.java:7127)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 19044 SIG: 9

**Comment by juniorojha** [comment]
I am also facing the same issue, any idea why this is happening? The crop picker works on all other devices except mine. My Android version is 9 (Pie), is that reason for this behaviour? What is your Android version?

**Comment by uforujjwal** [comment]
@juniorojha I got the issue fixed by creating a release apk by using ./gradlew assembleRelease, so this works only with release apk and not debug apk for me as of now

**Comment by juniorojha** [comment]
> @juniorojha I got the issue fixed by creating a release apk by using ./gradlew assembleRelease, so this works only with release apk and not debug apk for me as of now

Does it work on Android 9? Because we're also able to get it work in release (crashes sometimes in debug on the crop screen) for Android 8 and and earlier.

**Comment by uforujjwal** [comment]
@juniorojha  Yes it works fine on Android 9, it always fails on every android version for debug apk on crop screen.
Also did you tweak the UI or modify the slider behaviour, I need to do that and need some advice/insight on this

**Comment by juniorojha** [comment]
@uforujjwal unfortunately I did not tweak the UI but had to do away with the cropping feature altogether for Android 9 otherwise it caused the app to crash :(

**Comment by uforujjwal** [comment]
@juniorojha May I know which library did you switch to??

**Comment by juniorojha** [comment]
@uforujjwal I am continuing to use the react-native-image-crop-picker but have set crop parameter to false in case of Android 9.

**Comment by uforujjwal** [comment]
Thanks for the info @juniorojha

**Comment by uforujjwal** [comment]
Upgrading react-native to 58 solves the issue

**Comment by fathima-shamsu** [comment]
doesnt work in android 6.0
