### ISSUE TITLE
App aborts on Android while opening image picker

### ISSUE THREAD

**Issue by varungupta85** [ivpusic/react-native-image-crop-picker#97]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.9.7
- react-native v0.34.1

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
Show an image picker

### Actual behaviour
App crashes and an alert is shown that the app has stopped on the phone

### Steps to reproduce

Show image picker on click of a button in an android app and I see an abort. Weirdly, if I dismiss the red screen, I see the image picker in the background but ofcourse it is not attached to the app at that point. Looking at the call stack, it looks like for some reason, it thinks that we are trying to call an abstract method `onActivityResult` which has not been implemented but it is clearly implemented in the `PickerModule`

### Attachments
```

10-06 11:40:43.365 10296-10296/com.galarmapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.galarmapp, PID: 10296
                                                               java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
                                                                   at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
                                                                   at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:616)
                                                                   at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
                                                                   at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
                                                                   at android.app.Activity.dispatchActivityResult(Activity.java:6428)
                                                                   at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                   at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ivpusic** [comment]
please ensure that you are using RN v0.34.1. If you used some older version before, and you recently upgraded, probably upgrade it not yet fully applied on your project. Similar issue https://github.com/ivpusic/react-native-image-crop-picker/issues/50

**Comment by varungupta85** [comment]
It turns out that the module `react-native-image-picker` was somehow interfering with this package causing it to pick up an outdated react-native source jar. I am moving from using `react-native-image-picker` to this package because I am looking for the scale and crop feature provided in this package. Once I removed the package references from the gradle files, the error went away.

**Comment by xzdev** [comment]
I had the same issue using react-native-image-picker v.0.19. After upgrading it to v0.22.9, the crashing issue is gone.

**Comment by GopiKrishna10** [comment]
hi Guys,
i am still facing a issue when I take the picture and press OK button the app get restarted.in all mobiles like redmi note4 and moto g2. am trying to resolve from one day. am not able to solve this can u please help me thanks in advance @xzdev 

i update the version react-native-image-picker from 0.26.3 to 0.22.9. app getting like "unfortunately app has stopped" showing pop up like this.

config

"react-native": "^0.42.3",
"react-native-image-picker": "0.22.9"
db is firebase

options are

var options = {
title: 'Select Avatar',
quality: 0.6,
storageOptions: {
skipBackup: true,
path: 'images'
}
};

**Comment by rmamtaventures** [comment]
App restart on image select only in Redmi devices. Please suggest?
